apiVersion: v1
kind: Secret
metadata:
  name: medicos-secrets
  namespace: default
  labels:
    app: medicos-backend
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/medicos_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "admin"
  JWT_SECRET: "MedicosSecretKeySuperSecureJwtTokenSignatureKey2026WithAtLeast256BitsSecretKey!"
