package com.medicos.backend.service;

import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Map;

@Service
public class SystemService {

    public Map<String, Object> getHealthCheck() {
        return Map.of(
                "status", "UP",
                "service", "medicos-java-backend",
                "timestamp", LocalDateTime.now().toString(),
                "database", "PostgreSQL"
        );
    }

    public Map<String, Object> getSystemStatus() {
        return Map.of(
                "status", "healthy",
                "version", "1.0.0",
                "engine", "Spring Boot 3 + PostgreSQL",
                "timestamp", LocalDateTime.now().toString()
        );
    }

    public Map<String, Object> getPrivacyPolicy() {
        return Map.of(
                "title", "Medbuilds Hospital EMR Privacy Policy",
                "effectiveDate", "2026-01-01",
                "version", "2.1.0",
                "compliance", "Digital Personal Data Protection (DPDP) Act 2023 & Ayushman Bharat Digital Mission (ABDM)",
                "summary", "Medbuilds Hospital EMR safeguards all patient electronic health records (EHR) using AES-256 encryption at rest and TLS 1.3 in transit.",
                "sections", Map.of(
                        "dataCollected", "Demographic details, vital signs, clinical encounters, diagnostic reports, and digital prescriptions.",
                        "purposeOfUse", "Strictly for clinical treatment, hospital billing, prescription fulfillment, and patient portal access.",
                        "dataRetention", "Medical records are retained securely in compliance with National Health Authority (NHA) & Medical Council guidelines.",
                        "patientRights", "Patients have the right to access, request corrections, and manage consent for record sharing across ABDM health networks."
                )
        );
    }

    public Map<String, Object> getTermsOfService() {
        return Map.of(
                "title", "Medbuilds Hospital EMR Terms of Service",
                "effectiveDate", "2026-01-01",
                "version", "2.1.0",
                "summary", "Terms governing access to Medbuilds EMR systems by healthcare providers, hospital staff, and patients.",
                "sections", Map.of(
                        "medicalDisclaimer", "Digital prescriptions and medical advice issued via Medbuilds EMR are generated by licensed healthcare professionals.",
                        "accountSecurity", "Authorized staff must maintain strict confidentiality of Multi-Factor Authentication (MFA) and credentials.",
                        "emergencyUse", "In critical medical emergencies, break-glass access logs will be audited for clinical accountability.",
                        "intellectualProperty", "All hospital branding, custom letterheads, and software architecture belong to Medbuilds EMR Systems."
                )
        );
    }
}
